import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Bolivian Flag Banner */}
        <div className="w-full flex flex-col shrink-0 shadow-sm relative z-50">
          <div className="w-full h-1.5 bg-indigo-500"></div>
          <div className="w-full h-1.5 bg-amber-500"></div>
          <div className="w-full h-1.5 bg-emerald-500"></div>
        </div>
        {children}
      </body>
    </html>
  );
}
